# Generated by Django 3.2.6 on 2021-08-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800)),
                ('author', models.CharField(max_length=80)),
                ('slug', models.SlugField()),
                ('content', models.TextField()),
            ],
        ),
    ]
